# Generated by Django 4.1.4 on 2023-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociados',
            fields=[
                ('rutAsociado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut del asociado')),
                ('tipoAsociado', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Asociado')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('correo', models.CharField(blank=True, max_length=50, verbose_name='Correo')),
                ('edad', models.IntegerField(blank=True, verbose_name='Edad')),
                ('telefono', models.IntegerField(blank=True, verbose_name='Teléfono')),
                ('comuna', models.CharField(blank=True, max_length=50, verbose_name='Comuna')),
            ],
        ),
    ]
