# Generated by Django 4.1.4 on 2023-06-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asociados',
            new_name='Asociado',
        ),
    ]
