# Generated by Django 4.1.4 on 2023-06-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_asociado_rutasociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de comuna')),
                ('nombreComuna', models.CharField(blank=True, max_length=50, verbose_name='Nombre de comuna')),
            ],
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('idSocio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de socio')),
                ('nombreSocio', models.CharField(blank=True, max_length=50, verbose_name='Nombre de socio')),
            ],
        ),
    ]
