# Generated by Django 4.1.4 on 2023-06-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_comuna_tiposocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.comuna', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='asociado',
            name='tipoAsociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.tiposocio', verbose_name='Tipo de Asociado'),
        ),
    ]
