# Generated by Django 4.1.4 on 2023-06-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_alter_asociado_comuna_alter_asociado_tipoasociado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Codigo del producto')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre de producto')),
                ('precio', models.CharField(blank=True, max_length=100, verbose_name='Precio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto', verbose_name='foto')),
            ],
        ),
    ]
